export type BangladeshDistrict = {
  district: string;
  zone: "Inside Dhaka" | "Outside Dhaka";
  areas: string[];
};

export const bangladeshLocations: BangladeshDistrict[] = [
  { district: "Dhaka", zone: "Inside Dhaka", areas: ["Mirpur", "Dhanmondi", "Gulshan", "Banani", "Uttara", "Mohammadpur", "Badda", "Motijheel", "Wari", "Jatrabari", "Savar", "Keraniganj", "Dohar", "Nawabganj", "Dhamrai"] },
  { district: "Faridpur", zone: "Outside Dhaka", areas: ["Faridpur Sadar", "Boalmari", "Alfadanga", "Bhanga", "Charbhadrasan", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"] },
  { district: "Gazipur", zone: "Outside Dhaka", areas: ["Gazipur Sadar", "Tongi", "Kaliakair", "Kapasia", "Kaliganj", "Sreepur"] },
  { district: "Gopalganj", zone: "Outside Dhaka", areas: ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"] },
  { district: "Kishoreganj", zone: "Outside Dhaka", areas: ["Kishoreganj Sadar", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimganj", "Katiadi", "Kuliarchar", "Mithamain", "Nikli", "Pakundia", "Tarail"] },
  { district: "Madaripur", zone: "Outside Dhaka", areas: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar", "Dasar"] },
  { district: "Manikganj", zone: "Outside Dhaka", areas: ["Manikganj Sadar", "Daulatpur", "Ghior", "Harirampur", "Saturia", "Shibalaya", "Singair"] },
  { district: "Munshiganj", zone: "Outside Dhaka", areas: ["Munshiganj Sadar", "Gazaria", "Lohajang", "Sirajdikhan", "Sreenagar", "Tongibari"] },
  { district: "Narayanganj", zone: "Outside Dhaka", areas: ["Narayanganj Sadar", "Araihazar", "Bandar", "Rupganj", "Sonargaon"] },
  { district: "Narsingdi", zone: "Outside Dhaka", areas: ["Narsingdi Sadar", "Belabo", "Monohardi", "Palash", "Raipura", "Shibpur"] },
  { district: "Rajbari", zone: "Outside Dhaka", areas: ["Rajbari Sadar", "Baliakandi", "Goalandaghat", "Pangsha", "Kalukhali"] },
  { district: "Shariatpur", zone: "Outside Dhaka", areas: ["Shariatpur Sadar", "Bhedarganj", "Damudya", "Gosairhat", "Naria", "Zajira", "Sakhipur"] },
  { district: "Tangail", zone: "Outside Dhaka", areas: ["Tangail Sadar", "Basail", "Bhuapur", "Delduar", "Dhanbari", "Ghatail", "Gopalpur", "Kalihati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur"] },
  { district: "Chattogram", zone: "Outside Dhaka", areas: ["Chattogram Sadar", "Agrabad", "Panchlaish", "Pahartali", "Anwara", "Banshkhali", "Boalkhali", "Chandanaish", "Fatikchhari", "Hathazari", "Lohagara", "Mirsharai", "Patiya", "Rangunia", "Raozan", "Sandwip", "Satkania", "Sitakunda"] },
  { district: "Cox's Bazar", zone: "Outside Dhaka", areas: ["Cox's Bazar Sadar", "Chakaria", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhia"] },
  { district: "Bandarban", zone: "Outside Dhaka", areas: ["Bandarban Sadar", "Alikadam", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"] },
  { district: "Brahmanbaria", zone: "Outside Dhaka", areas: ["Brahmanbaria Sadar", "Akhaura", "Ashuganj", "Bancharampur", "Bijoynagar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"] },
  { district: "Chandpur", zone: "Outside Dhaka", areas: ["Chandpur Sadar", "Faridganj", "Haimchar", "Hajiganj", "Kachua", "Matlab North", "Matlab South", "Shahrasti"] },
  { district: "Cumilla", zone: "Outside Dhaka", areas: ["Cumilla Sadar", "Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Daudkandi", "Debidwar", "Homna", "Laksam", "Monohorgonj", "Meghna", "Muradnagar", "Nangalkot", "Titas"] },
  { district: "Feni", zone: "Outside Dhaka", areas: ["Feni Sadar", "Chhagalnaiya", "Daganbhuiyan", "Fulgazi", "Parshuram", "Sonagazi"] },
  { district: "Khagrachhari", zone: "Outside Dhaka", areas: ["Khagrachhari Sadar", "Dighinala", "Guimara", "Lakshmichhari", "Mahalchhari", "Manikchhari", "Matiranga", "Panchhari", "Ramgarh"] },
  { district: "Lakshmipur", zone: "Outside Dhaka", areas: ["Lakshmipur Sadar", "Kamalnagar", "Raipur", "Ramganj", "Ramgati"] },
  { district: "Noakhali", zone: "Outside Dhaka", areas: ["Noakhali Sadar", "Begumganj", "Chatkhil", "Companiganj", "Hatiya", "Kabirhat", "Senbagh", "Sonaimuri", "Subarnachar"] },
  { district: "Rangamati", zone: "Outside Dhaka", areas: ["Rangamati Sadar", "Baghaichhari", "Barkal", "Belaichhari", "Juraichhari", "Kaptai", "Kawkhali", "Langadu", "Naniarchar", "Rajasthali"] },
  { district: "Rajshahi", zone: "Outside Dhaka", areas: ["Rajshahi Sadar", "Bagha", "Bagmara", "Charghat", "Durgapur", "Godagari", "Mohanpur", "Paba", "Puthia", "Tanore"] },
  { district: "Bogura", zone: "Outside Dhaka", areas: ["Bogura Sadar", "Adamdighi", "Dhunat", "Dhupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Sariakandi", "Shajahanpur", "Sherpur", "Shibganj", "Sonatala"] },
  { district: "Chapai Nawabganj", zone: "Outside Dhaka", areas: ["Chapai Nawabganj Sadar", "Bholahat", "Gomastapur", "Nachole", "Shibganj"] },
  { district: "Joypurhat", zone: "Outside Dhaka", areas: ["Joypurhat Sadar", "Akkelpur", "Kalai", "Khetlal", "Panchbibi"] },
  { district: "Naogaon", zone: "Outside Dhaka", areas: ["Naogaon Sadar", "Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mohadevpur", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"] },
  { district: "Natore", zone: "Outside Dhaka", areas: ["Natore Sadar", "Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Naldanga", "Singra"] },
  { district: "Pabna", zone: "Outside Dhaka", areas: ["Pabna Sadar", "Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Santhia", "Sujanagar"] },
  { district: "Sirajganj", zone: "Outside Dhaka", areas: ["Sirajganj Sadar", "Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Raiganj", "Shahjadpur", "Tarash", "Ullahpara"] },
  { district: "Khulna", zone: "Outside Dhaka", areas: ["Khulna Sadar", "Batiaghata", "Dacope", "Dighalia", "Dumuria", "Koyra", "Paikgachha", "Phultala", "Rupsa", "Terokhada"] },
  { district: "Bagerhat", zone: "Outside Dhaka", areas: ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"] },
  { district: "Chuadanga", zone: "Outside Dhaka", areas: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"] },
  { district: "Jashore", zone: "Outside Dhaka", areas: ["Jashore Sadar", "Abhaynagar", "Bagherpara", "Chaugachha", "Jhikargachha", "Keshabpur", "Manirampur", "Sharsha"] },
  { district: "Jhenaidah", zone: "Outside Dhaka", areas: ["Jhenaidah Sadar", "Harinakunda", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"] },
  { district: "Kushtia", zone: "Outside Dhaka", areas: ["Kushtia Sadar", "Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Mirpur"] },
  { district: "Magura", zone: "Outside Dhaka", areas: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"] },
  { district: "Meherpur", zone: "Outside Dhaka", areas: ["Meherpur Sadar", "Gangni", "Mujibnagar"] },
  { district: "Narail", zone: "Outside Dhaka", areas: ["Narail Sadar", "Kalia", "Lohagara"] },
  { district: "Satkhira", zone: "Outside Dhaka", areas: ["Satkhira Sadar", "Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Shyamnagar", "Tala"] },
  { district: "Barishal", zone: "Outside Dhaka", areas: ["Barishal Sadar", "Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Gaurnadi", "Hizla", "Mehendiganj", "Muladi", "Wazirpur"] },
  { district: "Barguna", zone: "Outside Dhaka", areas: ["Barguna Sadar", "Amtali", "Bamna", "Betagi", "Patharghata", "Taltali"] },
  { district: "Bhola", zone: "Outside Dhaka", areas: ["Bhola Sadar", "Borhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"] },
  { district: "Jhalokathi", zone: "Outside Dhaka", areas: ["Jhalokathi Sadar", "Kathalia", "Nalchity", "Rajapur"] },
  { district: "Patuakhali", zone: "Outside Dhaka", areas: ["Patuakhali Sadar", "Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Rangabali"] },
  { district: "Pirojpur", zone: "Outside Dhaka", areas: ["Pirojpur Sadar", "Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur", "Nesarabad", "Zianagar"] },
  { district: "Sylhet", zone: "Outside Dhaka", areas: ["Sylhet Sadar", "Balaganj", "Beanibazar", "Bishwanath", "Companiganj", "Dakshin Surma", "Fenchuganj", "Golapganj", "Gowainghat", "Jaintiapur", "Kanaighat", "Zakiganj"] },
  { district: "Habiganj", zone: "Outside Dhaka", areas: ["Habiganj Sadar", "Ajmiriganj", "Bahubal", "Baniachong", "Chunarughat", "Lakhai", "Madhabpur", "Nabiganj", "Shaistaganj"] },
  { district: "Moulvibazar", zone: "Outside Dhaka", areas: ["Moulvibazar Sadar", "Barlekha", "Juri", "Kamalganj", "Kulaura", "Rajnagar", "Sreemangal"] },
  { district: "Sunamganj", zone: "Outside Dhaka", areas: ["Sunamganj Sadar", "Bishwamvarpur", "Chhatak", "Derai", "Dharamapasha", "Dowarabazar", "Jagannathpur", "Jamalganj", "Shalla", "Tahirpur"] },
  { district: "Rangpur", zone: "Outside Dhaka", areas: ["Rangpur Sadar", "Badarganj", "Gangachara", "Kaunia", "Mithapukur", "Pirgachha", "Pirganj", "Taraganj"] },
  { district: "Dinajpur", zone: "Outside Dhaka", areas: ["Dinajpur Sadar", "Birampur", "Birganj", "Biral", "Bochaganj", "Chirirbandar", "Fulbari", "Ghoraghat", "Hakimpur", "Kaharole", "Khansama", "Nawabganj", "Parbatipur"] },
  { district: "Gaibandha", zone: "Outside Dhaka", areas: ["Gaibandha Sadar", "Fulchhari", "Gobindaganj", "Palashbari", "Sadullapur", "Saghata", "Sundarganj"] },
  { district: "Kurigram", zone: "Outside Dhaka", areas: ["Kurigram Sadar", "Bhurungamari", "Char Rajibpur", "Chilmari", "Phulbari", "Nageshwari", "Rajarhat", "Raomari", "Ulipur"] },
  { district: "Lalmonirhat", zone: "Outside Dhaka", areas: ["Lalmonirhat Sadar", "Aditmari", "Hatibandha", "Kaliganj", "Patgram"] },
  { district: "Nilphamari", zone: "Outside Dhaka", areas: ["Nilphamari Sadar", "Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Saidpur"] },
  { district: "Panchagarh", zone: "Outside Dhaka", areas: ["Panchagarh Sadar", "Atwari", "Boda", "Debiganj", "Tetulia"] },
  { district: "Thakurgaon", zone: "Outside Dhaka", areas: ["Thakurgaon Sadar", "Baliadangi", "Haripur", "Pirganj", "Ranisankail"] },
  { district: "Mymensingh", zone: "Outside Dhaka", areas: ["Mymensingh Sadar", "Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon", "Gauripur", "Haluaghat", "Ishwarganj", "Muktagachha", "Nandail", "Phulpur", "Trishal"] },
  { district: "Jamalpur", zone: "Outside Dhaka", areas: ["Jamalpur Sadar", "Bakshiganj", "Dewanganj", "Islampur", "Madarganj", "Melandaha", "Sarishabari"] },
  { district: "Netrokona", zone: "Outside Dhaka", areas: ["Netrokona Sadar", "Atpara", "Barhatta", "Durgapur", "Khaliajuri", "Kalmakanda", "Kendua", "Madan", "Mohanganj", "Purbadhala"] },
  { district: "Sherpur", zone: "Outside Dhaka", areas: ["Sherpur Sadar", "Jhenaigati", "Nakla", "Nalitabari", "Sreebardi"] }
];
